# Site settings
title: ''
email: email@pankajparashar.com
description: "Hello. I am Pankaj Parashar, 25yrs old front-end designer and web developer from Mumbai, India."
baseurl: ""
url: "http://pankajparashar.com"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 15
permalink: /posts/:title
paginate_path: 'page/:num'

# Sass
sass:
  sass_dir: css
  style: :compressed