---
title: Pankaj Parashar — Developer. Designer. Writer.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: email@pankajparashar.com
description: 'Hello. I am Pankaj Parashar, 25yo frontend designer and web developer
  from Mumbai, India. I make things for the web and write about them on my blog here.

'
baseurl: ''
url: http://pankajparashar.com
twitter_username: pankajparashar
github_username: pankajparashar
markdown: kramdown
permalink: "/posts/:title/"
paginate: 15
paginate_path: page/:num
sass:
  sass_dir: css
  style: :compressed
gems:
- jekyll-sitemap
- jekyll-paginate
