# Site settings
title: Pankaj Parashar - Developer. Designer. Writer.
email: email@pankajparashar.com
description: "I'm 25yo frontend designer and web developer from Mumbai, India. I make things for the web and write about them on my blog here."
baseurl: ""
url: "http://pankajparashar.com"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 15
permalink: /posts/:title
paginate_path: 'page/:num'

# Sass
sass:
  sass_dir: css
  style: :compressed